version: "3"

services:
  postgres:
    image: postgres:9.6
    container_name: "db-teste-semob"
    environment:
      - POSTGRES_USER=db-teste-semob
      - POSTGRES_PASSWORD=db-teste
      - TZ=GMT-3
    volumes:
      - "./data/postgres:/var/lib/postgres/data"
    ports:
      - 5432:5432
    networks:
      - teste-semob-networks
    
  teste-semob:
    container_name: teste-semob-front
    networks:
      - teste-semob-networks
    build: "./frontend"
    ports:
      - 4200:4200


networks:
  teste-semob-networks:
    driver: bridge