version: "3"

services:
  postgres:
    image: postgres:9.6
    container_name: "db-teste-semob"
    environment:
      - POSTGRES_USER=db-teste-semob
      - POSTGRES_PASSWORD=db-teste
      - TZ=GMT-3
    volumes:
      - "./data/postgres:/var/lib/postgres/data"
    ports:
      - 5432:5432
    networks:
      - teste-semob-networks

  semob-api:
    restart: on-failure:10
    container_name: semob-api
    build: "./backend"
    depends_on:
      - postgres
    networks:
      - teste-semob-networks
    environment:
      - PORT=8080
      - SPRING_APPLICATION_NAME=teste-semob-backend
      - DB_HOST=postgres
      - DB_NAME=db-teste-semob
      - POSTGRES_USER=db-teste-semob
      - POSTGRES_PASSWORD=db-teste
      - DB_PORT=5432
    ports:
      - 8080:8080
    
  teste-semob:
    container_name: teste-semob-front
    depends_on:
      - semob-api
    networks:
      - teste-semob-networks
    build: "./frontend"
    ports:
      - 4200:4200


networks:
  teste-semob-networks:
    driver: bridge