server:
  port: ${PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:teste-semob-backend}
  jackson:
    time-zone: America/Sao_Paulo

  datasource:
    username: ${DB_USER:db-teste-semob}
    password: ${DB_PASSWORD:db-teste}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db-teste-semob}

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true